spring:
  application:
    name: tlias-web-management
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: pin666
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucket-name: java-web-exercise
    region: cn-guangzhou


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

