spring:
  application:
    name: springboot-mybatis-quickstart
  datasource:
    url: jdbc:mysql://localhost:3306/web01
    username: root
    password: pin666
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
